# Generated by Django 4.1.2 on 2023-01-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_db',
            old_name='username',
            new_name='name',
        ),
    ]
