# Generated by Django 4.1.2 on 2023-01-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_cat_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_profile')),
            ],
        ),
        migrations.AlterField(
            model_name='cat_db',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
