# Generated by Django 4.1.2 on 2023-01-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_item_db_alter_cat_db_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('need', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
